name: "Test Auto Comment Workflow"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write   # required to comment on PRs

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Add a comment to pull request (for testing)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs");
            const path = require("path");

            const pr_number = context.payload.pull_request.number;
            const pr_author = context.payload.pull_request.user.login;
            const repo_owner = context.repo.owner;

            const message = fs.readFileSync(
              path.join(process.env.GITHUB_WORKSPACE, ".github/ISSUE_GREETING.md"),
              "utf8"
            );

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr_number,
                body: `[TEST MODE] 👋 Workflow ran successfully!\n\n${message}`
              });
